config/routes.rb
Bachelorette::Application.routes.draw do
  resources :pins

  devise_for :users
root 'pages#home'
get "about" =>"pages#about"
get "signup" => "pages#signup"
get "step2" => "pages#step2"
get "faq" => "pages#faq"
get "login" => "pages#login"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", 
		:thumb => "100x100>" }
		validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
   def about
  end
  def faq
  end
  def signup
  end
  def login
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      
      </button>
      <%= link_to "Gprise", root_path, class: "navbar-brand" %>
    </div>
  
  <div class ="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
       <li><%= link_to "Home", root_path %></li>
       <li><%= link_to "About", about_path %></li>
       <li><%= link_to "FAQ", faq_path %></li>
        
        <% if user_signed_in? %> 
        <li><%= link_to "Settings", edit_user_registration_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete%></li> 
        <% else %>
        <li><%= link_to "Log In", new_user_session_path %></li> 
        <% end %>
      </ul>
    </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gprise</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
	<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %> 

<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>

    <div class = "container">
		<%= yield %>
  </div>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About</ht>
<p> paragraph about us </p>

app/views/pages/faq.html.erb
<h1>FAQ</h1>
<ul>

</ul>

app/views/pages/home.html.erb
<div class="jumbotron">
	<div class="container">
  <h1>Headline</h1>
  <p>Awesome tagline here</p>
<div class="container">
<!-- <form class="form-inline" role="form">
  <div class="form-group">
    <label class="sr-only" for="exampleInputEmail2">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Email">
  </div>
  <div class="form-group">
    <label class="sr-only" for="exampleInputPassword2">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Password">
  </div> -->

<% if user_signed_in? %>
# do something
<% else %>
<p>
  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
   <%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-lg" %>
 </p>
 <% end %>


</form>
</div>
</div>
</div>

app/views/pages/login.html.erb
<div class="container">
<form class="form-inline" role="form">
  <div class="form-group">
    <label class="sr-only" for="exampleInputEmail2">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Email">
  </div>
  <div class="form-group">
    <label class="sr-only" for="exampleInputPassword2">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Password">
  </div>
  <button type="submit" class="btn btn-default">Log In</button>
  
</form>
</div>

app/views/pages/signup.html.erb
<div class="container">
	<div class="progress progress-striped active">
  <div class="progress-bar"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 25%">
    <span class="sr-only">5% Complete</span>
  </div>
  </div>
<h1>Step 1: Choose Dates</h1>



</div>

app/views/pages/step2.html.erb
<div class="container">
	<div class="progress progress-striped active">
  <div class="progress-bar"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
    <span class="sr-only">5% Complete</span>
  </div>
  </div>
<h1>Step 1: Choose Dates</h1>
<input class="datepicker" data-date-format="mm/dd/yyyy">


</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
<!--   <div class="field"> -->
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <!-- <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div> -->
 
  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>Editing pin</h1>
	</div>

<div class="panel-body">
<%= render 'form' %> </div>


 <div class="panel-footer">
<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>
</div>

app/views/pins/index.html.erb
<h1>Listing pins</h1>
 
<table class ="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Description</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= image_tag pin.image.url(:medium) %></td>
        <td><%= pin.description %></td>
        <td><%= pin.user.email if pin.user %></td>
        <td><%= link_to 'Show', pin_path(pin) %></td>
        <% if pin.user == current_user %>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %> 
<%= link_to 'New Pin', new_pin_path %>
<% end %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= image_tag @pin.image.url(:medium) %>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<p>
  <strong>String:</strong>
  <%= @pin.string %>
</p>

<% if @pin.user == current_user %>
<%= link_to 'Edit', edit_pin_path(@pin) %> 
<% end %>
<%= link_to 'Back', pins_path %>